use_frameworks!

platform :ios, '9.0'

target 'Model02_Example' do
  pod 'Model02', :path => '../'
  pod 'Model03', :path => '../../Model03'
  target 'Model02_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
